### ISSUE TITLE
Change instanceof

### ISSUE THREAD

**Issue by UltimateGG** [git-zodyac/mongoose#11]
Instead of `instanceof` checks which break in monorepos, there are fields on the Zod objects with the type as a string.
See https://github.com/colinhacks/zod/issues/2241

Specifically, https://github.com/colinhacks/zod/issues/2241#issuecomment-2142688925 may work.

**Comment by bebrasmell** [comment]
Oi! Nice one. Will do.

**Comment by bebrasmell** [comment]
Hey! Good news, I've changed that behaviour with the latest 2.3.1 release.
