### ISSUE TITLE
[Question] How do you handle unique fields ?

### ISSUE THREAD

**Issue by AlexandreBrayer** [git-zodyac/mongoose#2]
I wonder how to handle unique fields. Do you have to delcare them after calling the function "zodSchema" ?

**Comment by AlexandreBrayer** [comment]
For more context : 
I tried
`const UserSchema = z.object({
	username: z.string(),
	email: z.string(),
	password: z.string(),
	role: z.enum(['user', 'admin']),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional()
});` 
then 
`const rawSchema = zodSchemaRaw(UserSchema);
rawSchema.email.unique = true;
rawSchema.username.unique = true;
`

`Property 'unique' does not exist on type '_Field<ZodString> | _Schema<ZodString>'.
  Property 'unique' does not exist on type '_Field<ZodString>'.ts(2339)`

Seems odd, since this code works

**Comment by AlexandreBrayer** [comment]
nvm i found it 
const schema = zodSchema(UserSchema);

schema.path('email').unique(true);
schema.path('username').unique(true);

**Comment by Kakha01** [comment]
@bebrasmell I think this issue is supposed to be closed no?
