### ISSUE TITLE
Transpilation Error

### ISSUE THREAD

**Issue by danilopalmisano** [git-zodyac/mongoose#4]
I'm using typescript in a node express project, im trying to export a zod object in to a mongoose model, but when I try to transcompile I get this message, any idea?

 const zod_mongoose_1 = require("@zodyac/zod-mongoose");
                       ^
 
 Error [ERR_REQUIRE_ESM]: require() of ES Module /home/danilo/project/Online-Music-Shop/node_modules/@zodyac/zod-mongoose/dist/index.js from /home/danilo/project/Online-Music-Shop/dist/validation/user.validation.js not supported.
Instead change the require of index.js in /home/danilo/project/Online-Music-Shop/dist/validation/user.validation.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/danilo/project/Online-Music-Shop/dist/validation/user.validation.js:5:24) {
  code: 'ERR_REQUIRE_ESM'

**Comment by bebrasmell** [comment]
Will investigate. I'm pretty sure I have CJS exports too.

**Comment by AndyReckt** [comment]
bump

**Comment by BenjaminLindberg** [comment]
Yeah I also experience this error. I downgraded to v 1.07 and it seems to work fine. But a lot more bugs in 1.07 sadly....

**Comment by BenjaminLindberg** [comment]
@way-zer yeah that's definitely the issue. I changed it to that in the module, and it works now.

**Comment by BenjaminLindberg** [comment]
#7

**Comment by bebrasmell** [comment]
Changes available in version 1.1.3
