### ISSUE TITLE
TS error 2589 : infinity

### ISSUE THREAD

**Issue by mathcovax** [git-zodyac/mongoose#6]
<img width="897" alt="Capture d’écran 2024-06-06 à 11 58 35" src="https://github.com/git-zodyac/mongoose/assets/98911237/a045c4be-f9a7-4ad0-ad05-4fd5646a65f0">
<img width="485" alt="Capture d’écran 2024-06-06 à 11 59 17" src="https://github.com/git-zodyac/mongoose/assets/98911237/50872f21-c514-423b-9af6-392341943260">

**Comment by Kakha01** [comment]
Can you paste the code so I can recreate the issue?

**Comment by bebrasmell** [comment]
Mongoose does not support records as for now
