### ISSUE TITLE
timestamps

### ISSUE THREAD

**Issue by fushugaku** [git-zodyac/mongoose#8]
With mongoose you can define timestamps like this
const userSchema = new Schema({ name: String }, { timestamps: true });

how can you do it when using this library?

**Comment by bebrasmell** [comment]
Hi @fushugaku!

For right now zod-mongoose does not have a first-class support for that feature, but that would be a cool enhancement. Please try using raw schema object to add necessary adjustments:

```ts
import { zodSchemaRaw } from '@zodyac/zod-mongoose';
import { model, Schema } from 'mongoose';

const schema = zodSchemaRaw(zDoc);
schema.age.timestamps = true;

const model = model('User', new Schema(schema));
```

**Comment by Kakha01** [comment]
I roughly got it working like this, however I'm not sure if it is typesafe

```ts
export function zodSchema<T extends ZodRawShape>(
  schema: ZodObject<T>,
  options?: SchemaOptions<FlatRecord<any>, {}, {}, {}, {}, any>
): Schema<z.infer<typeof schema>> {
  const definition = parseObject(schema);
  return new Schema<z.infer<typeof schema>>(definition, options);
}
```

SchemaOptions and FlatRecord come from 'mongoose' library

**Comment by bebrasmell** [comment]
Will be in next release
